### PR TITLE
Support SSL certificate path and expose auth parameters at a global level

### PR DESCRIPTION
**Pull request by gregswift**
We started utilizing this module yesterday instead of a simple bit that we had thrown together and immediately ran into a problem, but also a minor bit of duplicated effort.

Problem 1: Unable to use_ssl = true
  ES-py and curator use certifi for SSL certificates and that is not packaged for EL based distributions.  For our original work we just passed the CA certificate to curator directly, but this --certificate option wasn't handled by this module.

Problem 2: Having to pass user and password around when using ::job directly.
  Several of the parameters, such as host and port, can be set at the top level and then do not need to be passed to separate ::job calls.  Since these parameters are likely to be common for some users, I shifted things so that they are exposed at the top level as well.  Nothing in the behavior should change for existing users, but it does allow that use case.

I also extended the testing to cover my changes to address both options.

### CODE REVIEW

**Comment by gregswift** [comment]
And if you could cut a release to forge that would be awesome :)

**Comment by gregswift** [comment]
The tests are failing because of the puppet-lint-empty_string-check gem.  Many of them are in the module already.  The [module documentation](https://github.com/voxpupuli/puppet-lint-empty_string-check/blob/master/README.md) has recommendations for updating and disabling the check if the use case is valid

**Comment by jlambert121** [comment]
Thanks!

**Comment by gregswift** [comment]
I realize i striked out my release request. in retrospect i shouldnt have.  Any idea when you might cut next release?

**Comment by jlambert121** [comment]
@gregswift 2.3.0 pushed with this

**Comment by gregswift** [comment]
awesome! thank you

**Pull request merged**
